import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import ToasterProvider from "@/components/providers/ToasterProvider";
import HydrationProvider from "@/components/providers/HydrationProvider";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} antialiased`}>
        <ToasterProvider />
        <HydrationProvider>
          <Header />
          <main className="min-h-screen">{children}</main>
          <Footer />
        </HydrationProvider>
      </body>
    </html>
  );
}
